### ISSUE TITLE
Active player notification on startup overshadows controls

### ISSUE THREAD

**Issue by yannick** [orangebikelabs/opensqueeze#50]
When the app starts you cant quickly pause the player which is extremely inconvinient eg when kids turn up the volume ;)

**Comment by gharris999** [comment]
I'm finding that I'm not a fan of this feature as it now stands, either.  Often, when I start the app, it's because I want to quickly pause the music or change the volume.  The two second notification covering the playback & volume controls seems too long.  Any chance the notification time could be made shorter, e.g. half a second?  Or make it so the notification can be immediately dismissed with a press?

**Comment by bensandee** [comment]
Try the beta released yesterday, they move the notification so it doesn't obscure the controls.

**Comment by gharris999** [comment]
The beta with the changed notification position works perfectly for me. Thanks.

**Comment by bensandee** [comment]
Fixed in ca624a4f6316bd41b20a90843f0abbd3172f8c7e
